import numpy as np
arr = np.arange(5,17)
print(arr)
print(np.sqrt(arr))
x = np.random.rand(4)
y = np.random.rand(4)
print(x,y)
print(np.maximum(x,y))
arr = np.random.rand(5,4)
print(arr)
print(arr.sum())
print(arr.mean())
print(arr.sum(axis=0))
print(arr.sum(axis =1))
print(arr>0.5)
print((arr>0.5).sum())
arr = np.random.rand(5)
print(arr)
print(np.sort(arr))
print(np.sort(arr)[::-1])

arr = np.random.rand(150)
print(arr)
print(np.sort(arr))
print(np.sort(arr)[::-1][int(0.05*len(arr))])
ints = np.array([3,3,3,2,1,3,4,5,7,7,8])
print(np.unique(ints))

